prePareCartFlights = [
 'sc_appendconversiontype', 'sc_showvalidpis', 'sc_scdstextdirection',
 'sc_optimizecheckoutload', 'sc_purchasedblockedby', 'sc_passthroughculture',
 'sc_showcanceldisclaimerdefaultv1', 'sc_redirecttosignin',
 'sc_paymentpickeritem', 'sc_cleanreducercode', 'sc_dimealipaystylingfix',
 'sc_promocode', 'sc_onedrivedowngrade', 'sc_newooslogiconcart',
 'sc_optionalcatalogclienttype', 'sc_klarna', 'sc_hidecontactcheckbox',
 'sc_preparecheckoutrefactor', 'sc_checkoutklarna', 'sc_currencyformattingpkg',
 'sc_fullpageredirectionforasyncpi', 'sc_xaaconversionerror',
 'sc_promocodefeature-web-desktop', 'sc_eligibilityproducts',
 'sc_disabledpaymentoption', 'sc_enablecartcreationerrorparsing',
 'sc_purchaseblock', 'sc_returnoospsatocart', 'sc_dynamicseligibility',
 'sc_usebuynowonlyinternalendpoint', 'sc_removemoreless',
 'sc_renewalsubscriptionselector', 'sc_hidexdledd', 'sc_militaryshippingurl',
 'sc_xboxdualleaf', 'sc_japanlegalterms', 'sc_multiplesubscriptions',
 'sc_loweroriginalprice', 'sc_xaatovalenciastring',
 'sc_cannotbuywarrantyalone', 'sc_showminimalfooteroncheckout',
 'sc_checkoutdowngrade', 'sc_checkoutcontainsiaps', 'sc_localizedtax',
 'sc_officescds', 'sc_disableupgradetrycheckout', 'sc_extendPageTagToOverride',
 'sc_checkoutscenariotelemetry', 'sc_skipselectpi', 'sc_allowmpesapi',
 'sc_purchasestatusmessage', 'sc_storetermslink',
 'sc_postorderinfolineitemmessage', 'sc_addpaymentfingerprinttagging',
 'sc_shippingallowlist', 'sc_emptyresultcheck', 'sc_dualleaf',
 'sc_riskyxtoken', 'sc_abandonedretry', 'sc_testflightbuynow',
 'sc_addshippingmethodtelemetry', 'sc_leaficons', 'sc_newspinneroverlay',
 'sc_paymentinstrumenttypeandfamily', 'sc_addsitename',
 'sc_disallowalipayforcheckout', 'sc_checkoutsignintelemetry',
 'sc_prominenteddchange', 'sc_disableshippingaddressinit',
 'sc_preparecheckoutperf', 'sc_buynowctatext', 'sc_buynowuiprod',
 'sc_checkoutsalelegaltermsjp', 'sc_showooserrorforoneminute',
 'sc_proratedrefunds', 'sc_entitlementcheckallitems', 'sc_indiaregsbanner',
 'sc_checkoutentitlement', 'sc_rspv2', 'sc_focustrapforgiftthankyoupage',
 'sc_hideneedhelp', 'sc_defaultshippingref', 'sc_uuid',
 'sc_checkoutasyncpurchase', 'sc_nativeclientlinkredirect',
 'sc_enablelegalrequirements', 'sc_expanded.purchasespinner',
 'sc_valenciaupgrade', 'sc_enablezipplusfour', 'sc_giftingtelemetryfix',
 'sc_handleentitlementerror', 'sc_alwayscartmuid', 'sc_sharedupgrade',
 'sc_checkoutloadspinner', 'sc_xaaconversionexpirationdate',
 'sc_helptypescript', 'sc_newdemandsandneedsstatement',
 'sc_citizensoneallowed', 'sc_riskfatal', 'sc_renewtreatmenta',
 'sc_trialtreatmenta', 'sc_cartzoomfix', 'sc_useofficeonlyinternalendpoint',
 'sc_gotopurchase', 'sc_endallactivities', 'sc_headingheader', 'sc_flexsubs',
 'sc_useanchorcomponent', 'sc_addbillingaddresstelemetry',
 'sc_replacestoreappclient', 'sc_scenariotelemetryrefactor', 'sc_checkoutsmd',
 'sc_scenariosupportupdate', 'sc_bankchallengecheckout',
 'sc_addpaymenttelemetry', 'sc_railv2', 'sc_checkoutglobalpiadd',
 'sc_reactcheckout', 'sc_xboxgotocart', 'sc_hidewarningevents',
 'sc_xboxcomnosapi', 'sc_routebacktocartforoutofstock', 'sc_clientdebuginfo',
 'sc_koreanlegalterms', 'sc_refactorprorate', 'sc_paymentoptionnotfound',
 'sc_pidlflights', 'sc_fixcolorcontrastforrecommendeditems',
 'sc_hideeditbuttonwhenediting', 'sc_enablekakaopay', 'sc_ordercheckoutfix',
 'sc_xboxpmgrouping', 'sc_stickyfooter', 'sc_gotoredmrepl',
 'sc_partnernametelemetry', 'sc_jpregionconversion', 'sc_checkoutorderedpv',
 'sc_maxaddresslinelength', 'sc_componentexception', 'sc_buynowuipreload',
 'sc_updatebillinginfo', 'sc_newshippingmethodtelemetry',
 'sc_checkoutbannertelemetry', 'sc_learnmoreclcid', 'sc_satisfiedcheckout',
 'sc_checkboxarialabel', 'sc_newlegaltextlayout', 'sc_newpagetitle',
 'sc_prepaidcardsv3', 'sc_gamertaggifting', 'sc_checkoutargentinafee',
 'sc_xboxcomasyncpurchase', 'sc_sameaddressdefault',
 'sc_fixcolorcontrastforcheckout', 'sc_checkboxkg',
 'sc_usebuynowbusinesslogic', 'sc_skippurchaseconfirm',
 'sc_activitymonitorasyncpurchase', 'sc_shareddowngrade',
 'sc_allowedpisenabled', 'sc_xboxoos', 'sc_eligibilityapi',
 'sc_koreatransactionfeev1', 'sc_removesetpaymentmethod',
 'sc_ordereditforincompletedata', 'sc_cppidlerror', 'sc_bankchallenge',
 'sc_allowelo', 'sc_delayretry', 'sc_loadtestheadersenabled',
 'sc_migrationforcitizenspay', 'sc_conversionblockederror',
 'sc_allowpaysafecard', 'sc_purchasedblocked', 'sc_outofstock',
 'sc_selectpmonaddfailure', 'sc_allowcustompifiltering', 'sc_errorpageviewfix',
 'sc_windowsdevkitname', 'sc_xboxredirection',
 'sc_usebuynowonlynonprodendpoint', 'sc_getmoreinfourl',
 'sc_disablefilterforuserconsent', 'sc_suppressrecoitem', 'sc_dcccattwo',
 'sc_hipercard', 'sc_resellerdetail', 'sc_fixpidladdpisuccess',
 'sc_xdlshipbuffer', 'sc_allowverve', 'sc_inlinetempfix',
 'sc_ineligibletostate', 'sc_greenshipping', 'sc_trackinitialcheckoutload',
 'sc_creditcardpurge', 'sc_showlegalstringforproducttypepass',
 'sc_newduplicatesubserror', 'sc_xboxgamepad', 'sc_xboxspinner',
 'sc_xboxclosebutton', 'sc_xboxuiexp', 'sc_disabledefaultstyles',
 'sc_gamertaggifting'
]
purchaseFlights = [
 'sc_appendconversiontype', 'sc_showvalidpis', 'sc_scdstextdirection',
 'sc_optimizecheckoutload', 'sc_purchasedblockedby', 'sc_passthroughculture',
 'sc_showcanceldisclaimerdefaultv1', 'sc_redirecttosignin',
 'sc_paymentpickeritem', 'sc_cleanreducercode', 'sc_dimealipaystylingfix',
 'sc_promocode', 'sc_onedrivedowngrade', 'sc_newooslogiconcart',
 'sc_optionalcatalogclienttype', 'sc_klarna', 'sc_hidecontactcheckbox',
 'sc_preparecheckoutrefactor', 'sc_checkoutklarna', 'sc_currencyformattingpkg',
 'sc_fullpageredirectionforasyncpi', 'sc_xaaconversionerror',
 'sc_promocodefeature-web-desktop', 'sc_eligibilityproducts',
 'sc_disabledpaymentoption', 'sc_enablecartcreationerrorparsing',
 'sc_purchaseblock', 'sc_returnoospsatocart', 'sc_dynamicseligibility',
 'sc_usebuynowonlyinternalendpoint', 'sc_removemoreless',
 'sc_renewalsubscriptionselector', 'sc_hidexdledd', 'sc_militaryshippingurl',
 'sc_xboxdualleaf', 'sc_japanlegalterms', 'sc_multiplesubscriptions',
 'sc_loweroriginalprice', 'sc_xaatovalenciastring',
 'sc_cannotbuywarrantyalone', 'sc_showminimalfooteroncheckout',
 'sc_checkoutdowngrade', 'sc_checkoutcontainsiaps', 'sc_localizedtax',
 'sc_officescds', 'sc_disableupgradetrycheckout', 'sc_extendPageTagToOverride',
 'sc_checkoutscenariotelemetry', 'sc_skipselectpi', 'sc_allowmpesapi',
 'sc_purchasestatusmessage', 'sc_storetermslink',
 'sc_postorderinfolineitemmessage', 'sc_addpaymentfingerprinttagging',
 'sc_shippingallowlist', 'sc_emptyresultcheck', 'sc_dualleaf',
 'sc_riskyxtoken', 'sc_abandonedretry', 'sc_testflightbuynow',
 'sc_addshippingmethodtelemetry', 'sc_leaficons', 'sc_newspinneroverlay',
 'sc_paymentinstrumenttypeandfamily', 'sc_addsitename',
 'sc_disallowalipayforcheckout', 'sc_checkoutsignintelemetry',
 'sc_prominenteddchange', 'sc_disableshippingaddressinit',
 'sc_preparecheckoutperf', 'sc_buynowctatext', 'sc_buynowuiprod',
 'sc_checkoutsalelegaltermsjp', 'sc_showooserrorforoneminute',
 'sc_proratedrefunds', 'sc_entitlementcheckallitems', 'sc_indiaregsbanner',
 'sc_checkoutentitlement', 'sc_rspv2', 'sc_focustrapforgiftthankyoupage',
 'sc_hideneedhelp', 'sc_defaultshippingref', 'sc_uuid',
 'sc_checkoutasyncpurchase', 'sc_nativeclientlinkredirect',
 'sc_enablelegalrequirements', 'sc_expanded.purchasespinner',
 'sc_valenciaupgrade', 'sc_enablezipplusfour', 'sc_giftingtelemetryfix',
 'sc_handleentitlementerror', 'sc_alwayscartmuid', 'sc_sharedupgrade',
 'sc_checkoutloadspinner', 'sc_xaaconversionexpirationdate',
 'sc_helptypescript', 'sc_newdemandsandneedsstatement',
 'sc_citizensoneallowed', 'sc_riskfatal', 'sc_renewtreatmenta',
 'sc_trialtreatmenta', 'sc_cartzoomfix', 'sc_useofficeonlyinternalendpoint',
 'sc_gotopurchase', 'sc_endallactivities', 'sc_headingheader', 'sc_flexsubs',
 'sc_useanchorcomponent', 'sc_addbillingaddresstelemetry',
 'sc_replacestoreappclient', 'sc_scenariotelemetryrefactor', 'sc_checkoutsmd',
 'sc_scenariosupportupdate', 'sc_bankchallengecheckout',
 'sc_addpaymenttelemetry', 'sc_railv2', 'sc_checkoutglobalpiadd',
 'sc_reactcheckout', 'sc_xboxgotocart', 'sc_hidewarningevents',
 'sc_xboxcomnosapi', 'sc_routebacktocartforoutofstock', 'sc_clientdebuginfo',
 'sc_koreanlegalterms', 'sc_refactorprorate', 'sc_paymentoptionnotfound',
 'sc_pidlflights', 'sc_fixcolorcontrastforrecommendeditems',
 'sc_hideeditbuttonwhenediting', 'sc_enablekakaopay', 'sc_ordercheckoutfix',
 'sc_xboxpmgrouping', 'sc_stickyfooter', 'sc_gotoredmrepl',
 'sc_partnernametelemetry', 'sc_jpregionconversion', 'sc_checkoutorderedpv',
 'sc_maxaddresslinelength', 'sc_componentexception', 'sc_buynowuipreload',
 'sc_updatebillinginfo', 'sc_newshippingmethodtelemetry',
 'sc_checkoutbannertelemetry', 'sc_learnmoreclcid', 'sc_satisfiedcheckout',
 'sc_checkboxarialabel', 'sc_newlegaltextlayout', 'sc_newpagetitle',
 'sc_prepaidcardsv3', 'sc_gamertaggifting', 'sc_checkoutargentinafee',
 'sc_xboxcomasyncpurchase', 'sc_sameaddressdefault',
 'sc_fixcolorcontrastforcheckout', 'sc_checkboxkg',
 'sc_usebuynowbusinesslogic', 'sc_skippurchaseconfirm',
 'sc_activitymonitorasyncpurchase', 'sc_shareddowngrade',
 'sc_allowedpisenabled', 'sc_xboxoos', 'sc_eligibilityapi',
 'sc_koreatransactionfeev1', 'sc_removesetpaymentmethod',
 'sc_ordereditforincompletedata', 'sc_cppidlerror', 'sc_bankchallenge',
 'sc_allowelo', 'sc_delayretry', 'sc_loadtestheadersenabled',
 'sc_migrationforcitizenspay', 'sc_conversionblockederror',
 'sc_allowpaysafecard', 'sc_purchasedblocked', 'sc_outofstock',
 'sc_selectpmonaddfailure', 'sc_allowcustompifiltering', 'sc_errorpageviewfix',
 'sc_windowsdevkitname', 'sc_xboxredirection',
 'sc_usebuynowonlynonprodendpoint', 'sc_getmoreinfourl',
 'sc_disablefilterforuserconsent', 'sc_suppressrecoitem', 'sc_dcccattwo',
 'sc_hipercard', 'sc_resellerdetail', 'sc_fixpidladdpisuccess',
 'sc_xdlshipbuffer', 'sc_allowverve', 'sc_inlinetempfix',
 'sc_ineligibletostate', 'sc_greenshipping', 'sc_trackinitialcheckoutload',
 'sc_creditcardpurge', 'sc_showlegalstringforproducttypepass',
 'sc_newduplicatesubserror', 'sc_xboxgamepad', 'sc_xboxspinner',
 'sc_xboxclosebutton', 'sc_xboxuiexp', 'sc_disabledefaultstyles',
 'sc_gamertaggifting'
]
